language: python

sudo: false

python:
  - "2.7"
  - "pypy"

addons:
  apt:
    packages:
    # Dependencies for pycurl compilation
    - libcurl4-openssl-dev
    - libssl-dev

install:
  - pip install tox-travis
script:
  - tox
